# Uncomment the next line to define a global platform for your project
platform :ios, '1.0'

target 'FlowerClassifierML' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlowerClassifierML
  
pod 'Alamofire'
pod 'SwiftyJSON', '~> 4.0'

end
